/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * HeliTechnology Example Api
 * OpenAPI spec version: 1.0.0
 */
import type { PostAuthLogin422Errors } from './postAuthLogin422Errors';

export type PostAuthLogin422 = {
  errors?: PostAuthLogin422Errors;
  message?: string;
};
