/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * HeliTechnology Example Api
 * OpenAPI spec version: 1.0.0
 */
import type { PostAuthRegister422Errors } from './postAuthRegister422Errors';

export type PostAuthRegister422 = {
  errors?: PostAuthRegister422Errors;
  message?: string;
};
