/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * HeliTechnology Example Api
 * OpenAPI spec version: 1.0.0
 */

export interface User {
  email?: string;
  id?: number;
  name?: string;
}
